# This workflow will install Python dependencies, run tests and lint with a single version of Python
name: Docker C++ build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      -
        name: Build
        run: |
          cd sdk/cpp
          docker build . # will run buildx
